
var Movies0 = [ 
{ id: 1,
  name:'Once Upon a Time in the West',
  rating: '8.7',
  director: 'Sergio Leone',
  year: '1968',
  actor: 'Henry Fonda' },
{ id: 2,
  name:'Terminator 2: Judgment Day',
  rating: '8.6',
  director: 'James Cameron',
  year: '1991',
  actor: 'Arnold Schwarzenegger' },
{ id: 3,
  name:'Braveheart',
  rating: '8.4',
  director: 'Mel Gibson',
  year: '1995',
  actor: 'Mel Gibson' },
{ id: 4,
  name:'Oldboy',
  rating: '8.4',
  director: 'Chan-wook Park',
  year: '2003',
  actor: 'Min-sik Choi' },
{ id: 5,
  name:'Witness for the Prosecution',
  rating: '8.4',
  director: 'Billy Wilder',
  year: '1957',
  actor: 'Tyrone Power' },
{ id: 6,
  name:'Chinatown',
  rating: '8.4',
  director: 'Roman Polanski',
  year: '1974',
  actor: 'Jack Nicholson' },
{ id: 7,
  name:'Amadeus',
  rating: '8.4',
  director: 'Milos Forman',
  year: '1984',
  actor: 'F. Murray Abraham' },
{ id: 8,
  name:'Cool Hand Luke',
  rating: '8.2',
  director: 'Stuart Rosenberg',
  year: '1967',
  actor: 'Paul Newman' },
{ id: 9,
  name:'Ran',
  rating: '8.3',
  director: 'Akira Kurosawa',
  year: '1985',
  actor: 'Tatsuya Nakadai' },
{ id: 10,
  name:'Warrior',
  rating: '8.2',
  director: 'Gavin O\'Connor',
  year: '2011',
  actor: 'Tom Hardy' },
{ id: 11,
  name:'Butch Cassidy and the Sundance Kid',
  rating: '8.2',
  director: 'George Roy Hill',
  year: '1969',
  actor: 'Paul Newman' },
{ id: 12,
  name:'Into the Wild',
  rating: '8.2',
  director: 'Sean Penn',
  year: '2007',
  actor: 'Emile Hirsch' },
{ id: 13,
  name:'The Night of the Hunter',
  rating: '8.2',
  director: 'Charles Laughton',
  year: '1955',
  actor: 'Robert Mitchum' },
{ id: 14,
  name:'Persona',
  rating: '8.2',
  director: 'Ingmar Bergman',
  year: '1966',
  actor: 'Bibi Andersson' },
{ id: 15,
  name:'The Killing',
  rating: '8.1',
  director: 'Stanley Kubrick',
  year: '1956',
  actor: 'Sterling Hayden' },
{ id: 16,
  name:'Inherit the Wind',
  rating: '8.1',
  director: 'Stanley Kramer',
  year: '1960',
  actor: 'Spencer Tracy' },
{ id: 17,
  name:'8½',
  rating: '8.1',
  director: 'Federico Fellini',
  year: '1963',
  actor: 'Marcello Mastroianni' },
{ id: 18,
  name:'Anatomy of a Murder',
  rating: '8.1',
  director: 'Otto Preminger',
  year: '1959',
  actor: 'James Stewart' },
{ id: 19,
  name:'The Graduate',
  rating: '8.1',
  director: 'Mike Nichols',
  year: '1967',
  actor: 'Dustin Hoffman' },
{ id: 20,
  name:'The Man Who Shot Liberty Valance',
  rating: '8.1',
  director: 'John Ford',
  year: '1962',
  actor: 'James Stewart' },
{ id: 21,
  name:'The Wild Bunch',
  rating: '8.1',
  director: 'Sam Peckinpah',
  year: '1969',
  actor: 'William Holden' },
{ id: 22,
  name:'Roman Holiday',
  rating: '8.1',
  director: 'William Wyler',
  year: '1953',
  actor: 'Gregory Peck' },
{ id: 23,
  name:'Barry Lyndon',
  rating: '8.1',
  director: 'Stanley Kubrick',
  year: '1975',
  actor: 'Ryan O\'Neal' },
{ id: 24,
  name:'Rio Bravo',
  rating: '8.0',
  director: 'Howard Hawks',
  year: '1959',
  actor: 'John Wayne' },
{ id: 25,
  name:'Elite Squad: The Enemy Within',
  rating: '8.1',
  director: 'José Padilha',
  year: '2010',
  actor: 'Wagner Moura' },
{ id: 26,
  name:'Charade',
  rating: '8.0',
  director: 'Stanley Donen',
  year: '1963',
  actor: 'Cary Grant' },
{ id: 27,
  name:'What Ever Happened to Baby Jane?',
  rating: '8.0',
  director: 'Robert Aldrich',
  year: '1962',
  actor: 'Bette Davis' },
{ id: 28,
  name:'The Return',
  rating: '8.0',
  director: 'Andrey Zvyagintsev',
  year: '2003',
  actor: 'Vladimir Garin' },
{ id: 29,
  name:'Let the Right One In',
  rating: '8.0',
  director: 'Tomas Alfredson',
  year: '2008',
  actor: 'Kåre Hedebrant' },
{ id: 30,
  name:'The Big Heat',
  rating: '8.0',
  director: 'Fritz Lang',
  year: '1953',
  actor: 'Glenn Ford' },
{ id: 31,
  name:'Being There',
  rating: '8.0',
  director: 'Hal Ashby',
  year: '1979',
  actor: 'Peter Sellers' },
{ id: 32,
  name:'Shame',
  rating: '7.9',
  director: 'Ingmar Bergman',
  year: '1968',
  actor: 'Liv Ullmann' },
{ id: 33,
  name:'Jean de Florette',
  rating: '7.9',
  director: 'Claude Berri',
  year: '1986',
  actor: 'Yves Montand' },
{ id: 34,
  name:'This Is Spinal Tap',
  rating: '8.0',
  director: 'Rob Reiner',
  year: '1984',
  actor: 'Rob Reiner' },
{ id: 35,
  name:'Midnight Cowboy',
  rating: '8.0',
  director: 'John Schlesinger',
  year: '1969',
  actor: 'Dustin Hoffman' },
{ id: 36,
  name:'Days of Heaven',
  rating: '7.9',
  director: 'Terrence Malick',
  year: '1978',
  actor: 'Richard Gere' },
{ id: 37,
  name:'A Man for All Seasons',
  rating: '7.9',
  director: 'Fred Zinnemann',
  year: '1966',
  actor: 'Paul Scofield' },
{ id: 38,
  name:'A Raisin in the Sun',
  rating: '7.9',
  director: 'Daniel Petrie',
  year: '1961',
  actor: 'Sidney Poitier' },
{ id: 39,
  name:'Head-On',
  rating: '7.9',
  director: 'Fatih Akin',
  year: '2004',
  actor: 'Birol Ünel' },
{ id: 40,
  name:'No Man\'s Land',
  rating: '7.9',
  director: 'Danis Tanovic',
  year: '2001',
  actor: 'Branko Djuric' },
{ id: 41,
  name:'Miller\'s Crossing',
  rating: '7.9',
  director: 'Joel Coen',
  year: '1990',
  actor: 'Gabriel Byrne' },
{ id: 42,
  name:'The Sacrifice',
  rating: '7.9',
  director: 'Andrei Tarkovskij',
  year: '1986',
  actor: 'Erland Josephson' },
{ id: 43,
  name:'Crash',
  rating: '7.9',
  director: 'Paul Haggis',
  year: '2004',
  actor: 'Don Cheadle' },
{ id: 44,
  name:'Kagemusha',
  rating: '7.9',
  director: 'Akira Kurosawa',
  year: '1980',
  actor: 'Tatsuya Nakadai' },
{ id: 45,
  name:'Forbidden Games',
  rating: '7.9',
  director: 'René Clément',
  year: '1952',
  actor: 'Georges Poujouly' },
{ id: 46,
  name:'One, Two, Three',
  rating: '7.9',
  director: 'Billy Wilder',
  year: '1961',
  actor: 'James Cagney' },
{ id: 47,
  name:'Hud',
  rating: '7.9',
  director: 'Martin Ritt',
  year: '1963',
  actor: 'Paul Newman' },
{ id: 48,
  name:'4 Months, 3 Weeks and 2 Days',
  rating: '7.9',
  director: 'Cristian Mungiu',
  year: '2007',
  actor: 'Anamaria Marinca' },
{ id: 49,
  name:'Ferris Bueller\'s Day Off',
  rating: '7.9',
  director: 'John Hughes',
  year: '1986',
  actor: 'Matthew Broderick' },
{ id: 50,
  name:'The Iron Giant',
  rating: '7.9',
  director: 'Brad Bird',
  year: '1999',
  actor: 'Eli Marienthal' },
{ id: 51,
  name:'Kannathil Muthamittal',
  rating: '7.9',
  director: 'Mani Ratnam',
  year: '2002',
  actor: 'Madhavan' },
{ id: 52,
  name:'The Innocents',
  rating: '7.8',
  director: 'Jack Clayton',
  year: '1961',
  actor: 'Deborah Kerr' },
{ id: 53,
  name:'Diary of a Country Priest',
  rating: '7.8',
  director: 'Robert Bresson',
  year: '1951',
  actor: 'Claude Laydu' },
{ id: 54,
  name:'Simon',
  rating: '7.8',
  director: 'Eddy Terstall',
  year: '2004',
  actor: 'Cees Geel' },
{ id: 55,
  name:'The Man from Nowhere',
  rating: '7.8',
  director: 'Jeong-beom Lee',
  year: '2010',
  actor: 'Bin Won' },
{ id: 56,
  name:'Evil Dead II',
  rating: '7.8',
  director: 'Sam Raimi',
  year: '1987',
  actor: 'Bruce Campbell' },
{ id: 57,
  name:'Landscape in the Mist',
  rating: '7.8',
  director: 'Theodoros Angelopoulos',
  year: '1988',
  actor: 'Michalis Zeke' },
{ id: 58,
  name:'The World\'s Fastest Indian',
  rating: '7.8',
  director: 'Roger Donaldson',
  year: '2005',
  actor: 'Anthony Hopkins' },
{ id: 59,
  name:'Salaam Bombay!',
  rating: '7.8',
  director: 'Mira Nair',
  year: '1988',
  actor: 'Shafiq Syed' },
{ id: 60,
  name:'The Girl with the Dragon Tattoo',
  rating: '7.8',
  director: 'Niels Arden Oplev',
  year: '2009',
  actor: 'Michael Nyqvist' },
{ id: 61,
  name:'The Train',
  rating: '7.8',
  director: 'John Frankenheimer',
  year: '1964',
  actor: 'Burt Lancaster' },
{ id: 62,
  name:'The Edge of Heaven',
  rating: '7.8',
  director: 'Fatih Akin',
  year: '2007',
  actor: 'Baki Davrak' },
{ id: 63,
  name:'The Last Emperor',
  rating: '7.8',
  director: 'Bernardo Bertolucci',
  year: '1987',
  actor: 'John Lone' },
{ id: 64,
  name:'I Saw the Devil',
  rating: '7.8',
  director: 'Jee-woon Kim',
  year: '2010',
  actor: 'Byung-hun Lee' },
{ id: 65,
  name:'Johnny Got His Gun',
  rating: '7.8',
  director: 'Dalton Trumbo',
  year: '1971',
  actor: 'Timothy Bottoms' },
{ id: 66,
  name:'Serpico',
  rating: '7.8',
  director: 'Sidney Lumet',
  year: '1973',
  actor: 'Al Pacino' },
{ id: 67,
  name:'After the Wedding',
  rating: '7.7',
  director: 'Susanne Bier',
  year: '2006',
  actor: 'Mads Mikkelsen' },
{ id: 68,
  name:'True Grit',
  rating: '7.8',
  director: 'Ethan CoenJoel Coen',
  year: '2010',
  actor: 'Jeff Bridges' },
{ id: 69,
  name:'The Last of the Mohicans',
  rating: '7.7',
  director: 'Michael Mann',
  year: '1992',
  actor: 'Daniel Day-Lewis' },
{ id: 70,
  name:'A Place in the Sun',
  rating: '7.7',
  director: 'George Stevens',
  year: '1951',
  actor: 'Montgomery Clift' },
{ id: 71,
  name:'South Park: Bigger Longer & Uncut',
  rating: '7.7',
  director: 'Trey Parker',
  year: '1999',
  actor: 'Trey Parker' },
{ id: 72,
  name:'The Gospel According to St. Matthew',
  rating: '7.7',
  director: 'Pier Paolo Pasolini',
  year: '1964',
  actor: 'Enrique Irazoqui' },
{ id: 73,
  name:'Barton Fink',
  rating: '7.7',
  director: 'Joel Coen',
  year: '1991',
  actor: 'John Turturro' },
{ id: 74,
  name:'Kramer vs. Kramer',
  rating: '7.7',
  director: 'Robert Benton',
  year: '1979',
  actor: 'Dustin Hoffman' },
{ id: 75,
  name:'Mysterious Skin',
  rating: '7.7',
  director: 'Gregg Araki',
  year: '2004',
  actor: 'Brady Corbet' },
{ id: 76,
  name:'Guess Who\'s Coming to Dinner',
  rating: '7.7',
  director: 'Stanley Kramer',
  year: '1967',
  actor: 'Spencer Tracy' },
{ id: 77,
  name:'The Defiant Ones',
  rating: '7.7',
  director: 'Stanley Kramer',
  year: '1958',
  actor: 'Tony Curtis' },
{ id: 78,
  name:'The Court Jester',
  rating: '7.7',
  director: 'Melvin FrankNorman Panama',
  year: '1955',
  actor: 'Danny Kaye' },
{ id: 79,
  name:'Dead Man\'s Shoes',
  rating: '7.7',
  director: 'Shane Meadows',
  year: '2004',
  actor: 'Paddy Considine' },
{ id: 80,
  name:'The Taking of Pelham One Two Three',
  rating: '7.7',
  director: 'Joseph Sargent',
  year: '1974',
  actor: 'Walter Matthau' },
{ id: 81,
  name:'Forbidden Planet',
  rating: '7.7',
  director: 'Fred McLeod Wilcox',
  year: '1956',
  actor: 'Walter Pidgeon' },
{ id: 82,
  name:'Hamlet',
  rating: '7.7',
  director: 'Kenneth Branagh',
  year: '1996',
  actor: 'Kenneth Branagh' },
{ id: 83,
  name:'Star Trek II: The Wrath of Khan',
  rating: '7.7',
  director: 'Nicholas Meyer',
  year: '1982',
  actor: 'William Shatner' },
{ id: 84,
  name:'Black Hawk Down',
  rating: '7.7',
  director: 'Ridley Scott',
  year: '2001',
  actor: 'Josh Hartnett' },
{ id: 85,
  name:'Withnail & I',
  rating: '7.7',
  director: 'Bruce Robinson',
  year: '1987',
  actor: 'Richard E. Grant' },
{ id: 86,
  name:'The Haunting',
  rating: '7.7',
  director: 'Robert Wise',
  year: '1963',
  actor: 'Julie Harris' },
{ id: 87,
  name:'Kes',
  rating: '7.7',
  director: 'Kenneth Loach',
  year: '1969',
  actor: 'David Bradley' },
{ id: 88,
  name:'The Wicker Man',
  rating: '7.7',
  director: 'Robin Hardy',
  year: '1973',
  actor: 'Edward Woodward' },
{ id: 89,
  name:'Hugo',
  rating: '7.6',
  director: 'Martin Scorsese',
  year: '2011',
  actor: 'Asa Butterfield' },
{ id: 90,
  name:'Show Me Love',
  rating: '7.7',
  director: 'Lukas Moodysson',
  year: '1998',
  actor: 'Alexandra Dahlström' },
{ id: 91,
  name:'A Fish Called Wanda',
  rating: '7.6',
  director: 'Charles Crichton',
  year: '1988',
  actor: 'John Cleese' },
{ id: 92,
  name:'The Producers',
  rating: '7.6',
  director: 'Mel Brooks',
  year: '1968',
  actor: 'Zero Mostel' },
{ id: 93,
  name:'Hour of the Wolf',
  rating: '7.6',
  director: 'Ingmar Bergman',
  year: '1968',
  actor: 'Max von Sydow' },
{ id: 94,
  name:'Detachment',
  rating: '7.6',
  director: 'Tony Kaye',
  year: '2011',
  actor: 'Adrien Brody' },
{ id: 95,
  name:'A Pure Formality',
  rating: '7.6',
  director: 'Giuseppe Tornatore',
  year: '1994',
  actor: 'Gérard Depardieu' },
{ id: 96,
  name:'Marathon',
  rating: '7.7',
  director: 'Yoon-Chul Jeong',
  year: '2005',
  actor: 'Seung-woo Cho' },
{ id: 97,
  name:'Where Eagles Dare',
  rating: '7.6',
  director: 'Brian G. Hutton',
  year: '1968',
  actor: 'Richard Burton' },
{ id: 98,
  name:'The Spy Who Came in from the Cold',
  rating: '7.6',
  director: 'Martin Ritt',
  year: '1965',
  actor: 'Richard Burton' },
{ id: 9999,
  name:'日本人',
  rating: '7.6',
  director: '田中 太郎',
  year: '2000',
  actor: '山田 一郎' },
{ id: 100,
  name:'The Passion of Anna',
  rating: '7.6',
  director: 'Ingmar Bergman',
  year: '1969',
  actor: 'Liv Ullmann' } ];

var Movies = [Movies0];
